var app = angular.module('timetracker', ['ui.calendar']);

app.controller('ViewCtrl', function($scope, $http){
	
	$scope.$on('loadCourses', function(){
		$scope.loadCourses();
	});
	
	$scope.loadCourses = function(){
		$http.get('/course').success(function(data){
			$scope.courses = data;
		});
	};
	
	$scope.$on('loadTeachers', function(){
		$scope.loadTeachers();
	});
	
	$scope.loadTeachers = function(){
		$http.get('/teacher').success(function(data){
			$scope.teachers = data;
		});
	};
	
	$scope.loadSubjectsById = function() {
		var teacherId = $('#teacherId').val();
		$scope.subjects = [];
		angular.forEach($scope.teachers, function(teacher) {
			if (teacher.teacherId == teacherId) {
				angular.forEach(teacher.subjects, function(teacherSubject) {
					$scope.subjects.push(teacherSubject);
				});
			}
		});
	};
	
	 var date = new Date();
	 var d = date.getDate();
	 var m = date.getMonth();
	 var y = date.getFullYear();
	 var currentView = "month";
	
	//event source that pulls from google.com
    $scope.eventSource = {
    	
    };
	
    //to explicitly add events to the calendar
    //you can add the events in following ways
    $scope.events = [
      {title: 'All Day Event',start: new Date('Wed Feb 17 2016 09:00:00 GMT+0530 (IST)')},
      {title: 'Long Event',start: new Date('Wed Feb 17 2016 10:00:00 GMT+0530 (IST)'),end: new Date('Wed Feb 17 2016 17:00:00 GMT+0530 (IST)')},
      {id: 999,title: 'Repeating Event',start: new Date('Wed Feb 17 2016 09:00:00 GMT+0530 (IST)'),allDay: false},
      {id: 999,title: 'Repeating Event',start: new Date(y, m, d + 4, 16, 0),allDay: false},
      {title: 'Birthday Party',start: new Date(y, m, d + 1, 19, 0),end: new Date(y, m, d + 1, 22, 30),allDay: false},
      {title: 'Click for Google',start: new Date(y, m, 28),end: new Date(y, m, 29),url: 'http://google.com/'}
    ];
    
    //with this you can handle the click on the events
    $scope.eventClick = function(event){           
        $scope.$apply(function(){
          $scope.alertMessage = (event.title + ' is clicked');
        });
    };
     
    //with this you can handle the events that generated by each page render process
    $scope.renderView = function(view){    
        var date = new Date(view.calendar.getDate());
        $scope.currentDate = date.toDateString();
        $scope.$apply(function(){
          $scope.alertMessage = ('Page render with date '+ $scope.currentDate);
        });
    };
 
    //with this you can handle the events that generated when we change the view i.e. Month, Week and Day
    $scope.changeView = function(view,calendar) {
        currentView = view;
        calendar.fullCalendar('changeView',view);
        $scope.$apply(function(){
          $scope.alertMessage = ('You are looking at '+ currentView);
        });
    };
    
    /* config object */
    $scope.uiConfig = {
    	calendar:{
    		height: 450,
    		editable: true,
    		header:{
    			left: 'prev,next today',
	            center: 'title',
	            right: 'month,agendaWeek,agendaDay'
    		},
    		buttonText: {
	            today: 'today',
	            month: 'month',
	            week: 'week',
	            day: 'day'
			},
    		eventClick: $scope.eventClick,
    		viewRender: $scope.renderView
    	}
    };
    
    $scope.saveTimeTracker = function(){
		$http.post('/timetracker', $scope.timeTracker).success(function(){
			$scope.$emit('loadCourses');
			$scope.$emit('loadTeachers');
			$scope.$emit('loadCalendar');
			$scope.$emit('loadTimeTrackerEvents');
		});
	};
	
	$scope.loadCourses();
	$scope.loadTeachers();
	$scope.loadCalendar();
    
    /* event sources array*/
    $scope.eventSources = [$scope.events, $scope.eventSource];
});

function ini_events(ele){
	if (ele.length != 0) {
		ele.each(function(){
			var eventObject = { title: $.trim($('div.external-event').text()) };
			$('div.external-event').data('eventObject', eventObject);
			$('div.external-event').draggable({
				zIndex: 1070,
				revert: true, // will cause the event to go back to its
				revertDuration: 0  //  original position after the drag
			});
		})
	}
};

function allDayClicked() {
	var allDayCheckBoxVal = $("#allDay").is(':checked')?1:0;
	if (allDayCheckBoxVal == 1) {
		$('#startDate').hide();
		$('#endDate').hide();
		$('#startTime').hide();
		$('#endTime').hide();
	} else {
		$('#startDate').show();
		$('#endDate').show();
		$('#startTime').show();
		$('#endTime').show();
	}
};

function stringIt(val) {
    return JSON.stringify(val);
};
